In [6]:
import pandas as pd
import numpy as np

In [39]:

data = pd.read_csv("moviereviews.csv") 
movie_reviews = data.pivot_table(index='movie', columns='review', aggfunc='size', fill_value=0)
movie_vectors = movie_reviews.to_numpy()
print(movie_vectors)
dot_product_matrix = np.dot(movie_vectors.T, movie_vectors)
norms = np.linalg.norm(movie_vectors, axis=1)
print(norms)
def angle_between_vectors(vec1, vec2):
    dot_product = np.dot(vec1, vec2)
    angle = np.arccos(dot_product / (norms[vec1] * norms[vec2]))
    return angle
print(angle)

[[0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.57079633 1.57079633 1.57079633 1.57079633 1.57079633 1.57079633
 1.57079633 1.57079633 1.57079633 1.57079633 1.57079633 1.57079633
 1.57079633]


In [33]:
num_movies = len(movie_vectors)
top_pairs = []
for i in range(num_movies):
    for j in range(i + 1, num_movies):
        angle = angle_between_vectors(movie_vectors[i], movie_vectors[j])
        top_pairs.append((data['movie'][i], data['movie'][j], angle))

top_pairs.sort(key=lambda x: x[2][0])  
top_3_pairs = top_pairs[:3]

for pair in top_3_pairs:
    movie_i,movie_j, angle = pair
    print(f"Movies: {pair[0]} and {pair[1]}, Angle: {pair[2][0]}")

Movies: The Lord of the Rings The Two Towers and Inception, Angle: 1.5707963267948966
Movies: The Lord of the Rings The Two Towers and Spiderman Across the spider verse, Angle: 1.5707963267948966
Movies: The Lord of the Rings The Two Towers and The Dark Knight, Angle: 1.5707963267948966
