In [14]:
import numpy as np
patient_data = np.array([[76,126,38],
                [74,120,38],
                [72,118,37.5],
                [78,136,37]])
patient_data = np.array(patient_data,dtype=object)

print(patient_data)



[[76.0 126.0 38.0]
 [74.0 120.0 38.0]
 [72.0 118.0 37.5]
 [78.0 136.0 37.0]]


In [15]:
sum_of_patient = np.sum(patient_data, axis=0)
avg_patient = (sum_of_patient)/4
print(avg_patient)
vector_1 = patient_data[0] - avg_patient
print(vector_1)
vector_2 = patient_data[1] - avg_patient
print(vector_2)
vector_3 = patient_data[2] - avg_patient
print(vector_3)
vector_4 = patient_data[3] - avg_patient
print(vector_4)
avg_vector = np.array([[vector_1],
              [vector_2],
              [vector_3],
              [vector_4]])
print(avg_vector)





[75.0 125.0 37.625]
[1.0 1.0 0.375]
[-1.0 -5.0 0.375]
[-3.0 -7.0 -0.125]
[3.0 11.0 -0.625]
[[[1.0 1.0 0.375]]

 [[-1.0 -5.0 0.375]]

 [[-3.0 -7.0 -0.125]]

 [[3.0 11.0 -0.625]]]


In [16]:
def euclidean_distance(p1,p2):
    return np.sqrt(np.sum(p1 -p2 )**2)
num_avg_vector = avg_vector.shape[0]
farthest_patient = None
max_distance = -1
for i in range (num_avg_vector):
    distance_sum = np.sum([euclidean_distance(avg_vector[i],avg_vector[j]) for j in range( num_avg_vector) if i!=j])
    if distance_sum > max_distance:
        max_distance = distance_sum
        farthest_patient = i
print("The farthest patient is patient number =",farthest_patient)
nearest_patient = None
min_distance = float("inf")
for i in range (num_avg_vector):
    for j in range (i + 1 , num_avg_vector):
        distance = euclidean_distance(avg_vector[i],avg_vector[j])
        if distance < min_distance:
            min_distance = distance
            nearest_patient = i
print("The nearest patient is = " ,nearest_patient)

        


The farthest patient is patient number = 3
The nearest patient is =  1


In [29]:
dummy_patient = np.array([[78,138,38.0]])
patient_data_new = np.append(patient_data, dummy_patient,axis=0)
print(patient_data_new)

[[76.0 126.0 38.0]
 [74.0 120.0 38.0]
 [72.0 118.0 37.5]
 [78.0 136.0 37.0]
 [78.0 138.0 38.0]]


In [32]:
avg_patient_new = (np.sum(patient_data , axis=0))/4
print(avg_patient_new)
vector_1_new = patient_data_new[0] - avg_patient_new
vector_2_new = patient_data_new[1] - avg_patient_new
vector_3_new = patient_data_new[2] - avg_patient_new
vector_4_new = patient_data_new[3] - avg_patient_new
vector_5_new = patient_data_new[4] - avg_patient_new
avg_vector_new = np.array([[vector_1_new],
                        [vector_2_new],
                        [vector_3_new],
                        [vector_4_new],
                        [vector_5_new]])
print(avg_vector)

[75.0 125.0 37.625]
[[[1.0 1.0 0.375]]

 [[-1.0 -5.0 0.375]]

 [[-3.0 -7.0 -0.125]]

 [[3.0 11.0 -0.625]]]


In [33]:
def euclidean_distance(p1,p2):
    return np.sqrt(np.sum(p1 -p2 )**2)
num_avg_vector = avg_vector_new.shape[0]
nearest_patient = None
min_distance = float("inf")
for i in range (num_avg_vector):
    for j in range (i + 1 , num_avg_vector):
        distance = euclidean_distance(avg_vector_new[i],avg_vector_new[j])
        if distance < min_distance:
            min_distance = distance
            nearest_patient = i
print("The nearest patient is = " ,nearest_patient)

The nearest patient is =  3
